# This is the simple Travis configuration, which is intended for use
# on applications which do not require cross-platform and
# multiple-GHC-version support. For more information and other
# options, see:
#
# https://docs.haskellstack.org/en/stable/travis_ci/
#
# Copy these contents into the root directory of your Github project in a file
# named .travis.yml

# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

env:
  - HASKELL_GI_TYPELIB_SEARCH_PATH=/usr/lib/x86_64-linux-gnu/girepository-1.0

addons:
  apt:
    update: true
    packages:
      - ffmpeg
      - libavutil-dev
      - libavformat-dev
      - libavcodec-dev
      - libswscale-dev
      - libavdevice-dev
      - sox
      - libgirepository1.0-dev
      - libgtk-3-dev
      - libpango1.0-dev
      - libgdk-pixbuf2.0-dev
      # - gstreamer1.0-gtk3
      - gstreamer1.0-libav
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-good1.0-dev
      - libgstreamer-plugins-bad1.0-dev
    sources: [trusty-media]

# before_install:
#   - sudo apt-get update
#   - |
#     sudo apt-get install -y \
#       libgmp-dev \
#       pkg-config \
#       libavutil-dev \
#       libavformat-dev \
#       libavcodec-dev \
#       libswscale-dev \
#       libavdevice-dev \
#       ffmpeg \
#       sox \
#       libgirepository1.0-dev \
#       gstreamer1.0-gtk3 \
#       gstreamer1.0-libav \
#       libgstreamer1.0-0 \
#       libgstreamer-plugins-base1.0-dev \
#       libgstreamer-plugins-good1.0-dev \
#       libgstreamer-plugins-bad1.0-dev

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
# Build dependencies
- travis_retry stack install happy
- travis_retry stack --no-terminal --install-ghc test --only-dependencies

script:
# Build the package, its tests, and its docs and run the tests
- travis_retry stack --no-terminal test --haddock --no-haddock-deps